Hangry-App/Hangry

- README.md
> fix:readme updated

- Documentation/fourSquareApiResearch.md
Noted the API routes with sample paths we'll need for the app
Yes -  but we'll need to get some sample data later too...
No.
> Noted the API routes with sample paths we'll need for the app

- App.js
- components/Map.js
- components/index.js
Built map component and marker.
When you open the app it displays the map at your current location and a marker that's at your position
yes
no
> feat: app opens to map view that displays users location

- App.js
- components/UserLogIn.js
- components/index.js
- package-lock.json
- package.json
- secrets.js
- Set up a react native view for logging in. Saves log-in credentials to state and alerts to show that they're received. Also has an alert if a user tries to log in without setting up information.
- No. The login credentials are stored on local state right now, but will eventually need to be hooked up to Firebase login.
- Had to edit App.js to display the login. We'll need to change this so it has some type of react routing.
> Log in react component #13

- routes/fourSquare.js
- routes/menuResponse.json
- routes/venueDetailsResponse.json
Updated the routes with a working menu and details functionality.
Added sample data.
Yes, will need to decide how to merge the menu.
No - but you will need to update your secrets.js file
> Get foursquare sample data

- package.json
> fix: package json fixed. was missing comma

- secrets.js
> hiding my secrets

- routes/adilGetAllVenuesResponse.json
- routes/fourSquare.js
- routes/johnGetAllVenuesResponse.json
- routes/morganGetAllVenuesResponse.json
added sample data for each of our locations
yes - but John's location is missing data for menus
not enough menu information for us
> updated with sample data

- Documentation/Recomendation_test.js
Started work on recommendation functions
no
no
> feat: starting work on recomendation functions

- components/UserLogIn.js
- components/UserSignUp.js
- components/Welcome.js
Users stay logged in localy now.
yes
no...(dont think so)
> enhancement: user stays logged in localy

- package-lock.json
- package.json
Updated the package.json with three packages to fix the linter
Yes
No
> fix: update the install to fix the linter

- Documentation/Recomendation_test.js
Edited the Recomendation.js file in Documentation and its contents to create a funcitoning rating system.
for now
no
> enhancement: fixed rating system

- components/UserSignUp.js
Removed the extra bracket
Yes
The opposite
> Bug: Removed extra bracket

- components/Main.js
Set map region to follow the restaurant
Yep, unless we can figure out how to have the map always show BOTH the user and the restaurant
Nope.
> Map now follows the restaurant marker

- components/Cards.js
- components/Main.js
Wrote a function in Main.js that gets passed down to Cards.js so that on a swipe, it can change the offset of the map
Yep, but can be tweaked if needed
> Bug: Offset map when card is swiped up so locations aren't covered.

- App.js
- package-lock.json
App.js was defaulting to the user prefs page, I changed it back to the Welcome component
> Bug fix default page

- components/Main.js
- components/UserPref.js
- components/UserSignUp.js
- js/Recommendation_Engine.js
- package-lock.json
Organized navigation of the app.
probbably
dont think so
> Recommendation refractor

- components/Main.js
Pointed the dummy data reference to our gitignored file
Yep
Nope
> Pointed test data at the gitignored data file

- .firebaserc
- .gitignore
- firebase.json
- functions/.eslintrc.json
- functions/index.js
- functions/package-lock.json
- functions/package.json
- js/Recommendation_Engine.js
Initialized firebase cloud functions.
********npm install********
yes
Hopefully not
> feat: initialized firebase cloud functions

- components/Main.js
- components/Welcome.js
- functions/index.js
- js/Recommendation_Engine.js
Changed dummy data to johns
yep
nah
> Firebase initialization

- utils/getRestaurantInfo.js
Altered the util function to grab the price rating so it looks at `price.tier` now.
Yes.
> Bug: Fixes #66

- .prettierrc.json
- package-lock.json
Generated a prettierrc file for the project to share
Yep
> Generate prettierrc

- package.json
Added a 'start production' script that tunnels the expo server, and a 'start dev' script that sets the environment to development
Yes
> Added start scripts back in

- components/UserPref.js
Made the UI show the current state of the buttons that are selected.
Yes
No
> Ui show button state 77

- components/UserPref.js
Made the user prefs a bit clearer
Ya
Nope
> Ui user prefs reorder 81

- components/UserPref.js
no mo contractions
ya
just the coolness of usin' contractions...
> fix: closes #81 without a contraction...for real this time

- components/UserPref.js
Changed text color, fixed some spacing issues, changed button color when selected, and gave the back button absolute positioning
Yep
> Preference styling

- app.json
Added app.json back to project
You know it
Nope
> Fix: Added app.json back to root directory

- functions/index.js
- functions/source.js
fixed rounding error on savor score
yes
no
> fix: cleaned up rounding error on SavorScore™
